gitRepoUrl = "https://github.com/AnimalStudioOfficial/Crystal"

classOrder = [
    "CrystalServer",
    "CrystalClient"
]

[home]
enabled = true
includeReadme = false

[docusaurus]
tagline = "lightweight game framework For Roblox derived from Knit by Sleitnick."
favicon = "/favicon.png"
