[package]
name = "animalstudioofficial/crystal"
description = "lightweight game framework"
version = "0.8.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Comm = "sleitnick/comm@^0.3"
Promise = "evaera/promise@^4"
